/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sijamal.view;
import javax.swing.JOptionPane;
import sijamal.controller.*;
import sijamal.model.Peminjaman;

/**
 *
 * @author louis
 */
public class TinjauPeminjamanPanel extends javax.swing.JPanel {
    private Controller controller;
    private Peminjaman currentPeminjaman;
    /**
     * Creates new form TinjauPeminjaman
     */
    public TinjauPeminjamanPanel(Controller controller) {
        this.controller = controller;
        initComponents();
        this.currentPeminjaman = new Peminjaman();
    }
    
    public void setData(Peminjaman peminjaman) {
        this.currentPeminjaman = peminjaman;
        peminjamTextField.setText(peminjaman.getNimPeminjam());
        kategoriTextField.setText(peminjaman.getNamaKategori());
        namaalatTextField.setText(peminjaman.getNamaAlat());
        tanggalTextField.setText(peminjaman.getTanggalPinjam().toString());
        waktuTextField.setText(peminjaman.getWaktuPinjam().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        peminjamLabel = new javax.swing.JLabel();
        kategoriLabel = new javax.swing.JLabel();
        namaalatLabel = new javax.swing.JLabel();
        tanggalLabel = new javax.swing.JLabel();
        waktuLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        peminjamTextField = new javax.swing.JTextField();
        kategoriTextField = new javax.swing.JTextField();
        tanggalTextField = new javax.swing.JTextField();
        namaalatTextField = new javax.swing.JTextField();
        waktuTextField = new javax.swing.JTextField();
        statusComboBox = new javax.swing.JComboBox<>();
        perbaruiButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(27, 114, 191));
        setMaximumSize(new java.awt.Dimension(681, 474));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tinjau Peminjaman");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        peminjamLabel.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        peminjamLabel.setLabelFor(peminjamTextField);
        peminjamLabel.setText("Peminjam");

        kategoriLabel.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        kategoriLabel.setLabelFor(kategoriTextField);
        kategoriLabel.setText("Kategori");

        namaalatLabel.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        namaalatLabel.setLabelFor(namaalatTextField);
        namaalatLabel.setText("Nama Alat");

        tanggalLabel.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        tanggalLabel.setLabelFor(tanggalTextField);
        tanggalLabel.setText("Tanggal Peminjaman");

        waktuLabel.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        waktuLabel.setLabelFor(waktuTextField);
        waktuLabel.setText("Waktu Peminjaman");

        statusLabel.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        statusLabel.setLabelFor(statusLabel);
        statusLabel.setText("Status");

        peminjamTextField.setEditable(false);
        peminjamTextField.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N

        kategoriTextField.setEditable(false);
        kategoriTextField.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N

        tanggalTextField.setEditable(false);
        tanggalTextField.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N

        namaalatTextField.setEditable(false);
        namaalatTextField.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N

        waktuTextField.setEditable(false);
        waktuTextField.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N

        statusComboBox.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diajukan", "Disetujui", "Tidak Disetujui" }));
        statusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboBoxActionPerformed(evt);
            }
        });

        perbaruiButton.setBackground(new java.awt.Color(253, 207, 51));
        perbaruiButton.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        perbaruiButton.setText("Perbarui");
        perbaruiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perbaruiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(peminjamLabel)
                            .addComponent(kategoriLabel)
                            .addComponent(namaalatLabel)
                            .addComponent(tanggalLabel)
                            .addComponent(waktuLabel)
                            .addComponent(statusLabel))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(waktuTextField)
                            .addComponent(tanggalTextField)
                            .addComponent(kategoriTextField)
                            .addComponent(peminjamTextField)
                            .addComponent(namaalatTextField)
                            .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(perbaruiButton)
                        .addGap(95, 95, 95))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peminjamLabel)
                    .addComponent(peminjamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategoriLabel)
                    .addComponent(kategoriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaalatLabel)
                    .addComponent(namaalatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalLabel)
                    .addComponent(tanggalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waktuLabel)
                    .addComponent(waktuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(perbaruiButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void statusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboBoxActionPerformed

    private void perbaruiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perbaruiButtonActionPerformed
        // TODO add your handling code here:
        String newStatus = (String) statusComboBox.getSelectedItem();
        currentPeminjaman.setStatus(newStatus);
        controller.updatePeminjamanStatus(currentPeminjaman);
        JOptionPane.showMessageDialog(this, "Status berhasil diperbarui.");
        controller.showPeminjamanPanel();
    }//GEN-LAST:event_perbaruiButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kategoriLabel;
    private javax.swing.JTextField kategoriTextField;
    private javax.swing.JLabel namaalatLabel;
    private javax.swing.JTextField namaalatTextField;
    private javax.swing.JLabel peminjamLabel;
    private javax.swing.JTextField peminjamTextField;
    private javax.swing.JButton perbaruiButton;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel tanggalLabel;
    private javax.swing.JTextField tanggalTextField;
    private javax.swing.JLabel waktuLabel;
    private javax.swing.JTextField waktuTextField;
    // End of variables declaration//GEN-END:variables
}
